py_library(
    name = "calculator",
    srcs = ["calculator.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "calculator_test",
    deps = ["//projects/calculator:calculator"],
    srcs = ["calculator_test.py"],
)